apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zeebe-cluster.fullname" . }}
  labels:
{{- toYaml  .Values.labels | nindent 4 }}
spec:
  replicas: {{ .Values.clusterSize  }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: zeebe
  serviceName: {{ include "zeebe-cluster.fullname" . }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: zeebe
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ZEEBE_LOG_LEVEL
          value: debug
        - name: ZEEBE_PARTITIONS_COUNT
          value: {{ .Values.partitionCount | quote }}
        - name: ZEEBE_CLUSTER_SIZE
          value: {{ .Values.clusterSize | quote }}
        - name: ZEEBE_REPLICATION_FACTOR
          value: {{ .Values.replicationFactor | quote }}
        - name: JAVA_TOOL_OPTIONS
          value: 
           {{- toYaml .Values.JavaOpts | nindent 12}}
        ports:
        - containerPort: 9600
          name: http
        - containerPort: 26500
          name: gateway
        - containerPort: 26501
          name: command
        - containerPort: 26502
          name: internal
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 20
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /usr/local/zeebe/conf/zeebe.cfg.toml
          subPath: zeebe.cfg.toml
        - name: config
          mountPath: /usr/local/bin/startup.sh
          subPath: startup.sh
{{- if .Values.data.enabled }}
        - name: data
          mountPath: /usr/local/zeebe/data
{{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "zeebe-cluster.fullname" . }}
          defaultMode: 0744
{{- if .Values.data.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
{{ toYaml .Values.data.volumeClaimTemplate | indent 8 }}
{{- end }}
